### PR TITLE
Hi size

### PR DESCRIPTION
**Pull request by bwvdnbro**
This adds (in a not so clean but working way) a plot of the HI size vs HI mass.

Example of the plot (for a 6Mpc box with only 2 objects above the 1e9 Msun mass limit):
HI_size_mass

The methodology and comparison data comes from Rajohnson et al. (https://arxiv.org/abs/2203.06149). An HI surface density map is constructed using swiftsimio's subsampled backend. To this map, a 2D elliptical Gaussian profile is fit. The HI size is determined by measuring the diameter of the 1 Msun pc^-2 contour ellipse along the major axis. Here is an example of such a fit (the 1 Msun pc^-2 is plotted as a dashed line):
HI_size_0

The HI mass is computed by integrating the total surface density in the map.

### CODE REVIEW

**Comment by bwvdnbro** [comment]
After applying this to a larger simulation, I fixed some bugs. The most important one was that I forgot to rescale the smoothing length before calling swiftsimio, so that the surface density maps were much smoother than they should be (which helped with the Gaussian fit, but was just wrong).

More realistic fit example from the new version:
HI_size_17

This is what the HI mass - size relation looks like for the larger box:
HI_size_mass

Not quite as tight as the observed one. But then we have some really bad fits, like this one:
HI_size_0

**Comment by bwvdnbro** [comment]
@correac This pull request actually also contains the changes in #15, so you might want to merge that first.

**Comment by bwvdnbro** [comment]
This should be ready to go now.

**Comment by correac** [comment]
Great! Merging now.

**Pull request merged**
